# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tech Notes
email:
description: >- # this means to ignore newlines until "baseurl:"
  Useful notes about DevOps and system engineering

twitter_username: YYarmoshyk
github_username: yyarmoshyk
search: true
host: 0.0.0.0
repository: yyarmoshyk/tech-notes.net
incremental: false

# Build settings
markdown: kramdown
# markdown: CommonMark
# commonmark:
#    options: ["SMART", "FOOTNOTES"]
#    extensions: ["strikethrough", "autolink", "table"]

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

# Outputting
# permalink: /:categories/:title/
permalink: /:title/
paginate: 15 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _docs

collections:
  category:
    output: true

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-commonmark

author:
  name   : "Yaroslav Yarmoshyk"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I've got much to tell"
  # links:
  #   - label: "Website"
  #     icon: "fas fa-fw fa-link"
  #     url: "https://"
  #   - label: "Twitter"
  #     icon: "fab fa-fw fa-twitter-square"
  #     url: "https://twitter.com/"
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/"
  #   - label: "Instagram"
  #     icon: "fab fa-fw fa-instagram"
  #     url: "https://instagram.com/"

# footer:
#   links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: ""
    values:
      sidebar:
        nav: "docs"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
