name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the yyarmoshyk/jekyll-minimal-mistakes:ruby-2.5 container
      run: |
        docker run -t \
          -v ${{ github.workspace }}/public:/myblog/public \
          -v ${{ github.workspace }}/src:/myblog \
          jekyll/builder:latest \
          /bin/bash -c "chmod -R 777 /myblog && pwd && ls -la && cd /myblog && bundle && bundle exec jekyll build -d public"
